name: Firebase Deploy

on:
  push:
    branches: 
    - master
    - creating_gh_actions_deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
#      - name: Deploy assets to Firebase
#        uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          firebaseServiceAccount: ${{ secrets[env.FIREBASE_SERVICE_ACCOUNT_CARTO_GNEXT_21] }}
#          firebaseServiceAccount: ${{ secrets[env.FIREBASE_SERVICE_ACCOUNT] }}
#          target: default
#          channelId: live

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARTO_GNEXT_21 }}
